### ISSUE TITLE
I can't show html link tag properly in chat window. href is missing.

### ISSUE THREAD

**Issue by badis** [artemdemo/chat-ui#1]
I can't show html link tag properly in chat window. href is missing.
Can I enter any html code in messages ? for example to show cards video thumbnail, title , link ... etc.

**Comment by artemdemo** [comment]
Yes, it will be missing, since I'm [sanitizing input data](https://github.com/artemdemo/chat-ui/blob/e7199c7259b7d30c626cd6880d91003334e01484/source/components/Dialog.js#L44).

Please describe the use case, when it is a problem for you.

Thanks.

**Comment by badis** [comment]
Thank you for your reply.

I want to build a client for a bot where it's possible to display html boxes that contains links like this :https://cnet3.cbsistatic.com/img/s0StGKPNmRYwFt402PeIJWCHZnE=/fit-in/970x0/2016/07/26/4b043540-9608-49ea-a5a4-2c572aa1264b/1.png

Also (for example) when a user send a link to youtube video. it shows a video thumnail , title of video and link to that video.

I see there is a possibility to integrate images also but without links to external websites.

Thanks

**Comment by artemdemo** [comment]
You will need to upgrade my plugin, because even without sanitizing `chat-ui` is not supporting what you just described.
Feel free to fork it and make changes.

**Comment by badis** [comment]
Yes, I will fork it and make changes to it, but is it possible to show me where to configure sanitizer so it will not sanitize <a href=""></a> elements or disable it at all if not possible to do just that.

**Comment by artemdemo** [comment]
This part is not easy. I'm using [caja](https://github.com/google/caja) to sanitize input.
It has [2 files](https://github.com/artemdemo/chat-ui/tree/e7199c7259b7d30c626cd6880d91003334e01484/source/vendor):
* html-sanitizer.js
* html4-defs.js

`html4-defs.js` - is file with all sanitizing tests. In order to change it, you'll need to build it from source code of [caja](https://github.com/google/caja). For some reason, they don't use mainstream frontend technology, instead they use `ant`.

I used caja, because at the time it was best sanitizer I found.

May the force be with you.
